spring:
  datasource:
    username: wuyule
    password: qazwsx!@5201314..
    url: jdbc:mysql://45.40.234.228:3306/roles?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/example/demo/dao/.*xml
  type-aliases-package: com.example.demo

