spring:
  datasource:
    username: 
    password: 
    url: 
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/example/demo/dao/.*xml
  type-aliases-package: com.example.demo

